      SUBROUTINE MNQUAL(NGAGE,IHOUR,ICTT,TSURF,ihloc,jhloc)
!
!   QUALITY CONTROL ALGORITHM MAIN PROGRAM
!
!   CALLING SUBROUTINE: MAIN PROGRAM
!   SUBROUTINES CALLED: APREM,OUTREM
!
      DIMENSION RADAR(131,131)
      DIMENSION ICTT(15,15)
!
      COMMON/RADCOM/RADAR
      include 'ppinp'
      include 'raddat'
      INCLUDE 'bins'
      INCLUDE 'cnqu'
      include 'flags'
!
!   ANOMOLOUS PROPAGATION REMOVAL
!
!     IF(IFINST.EQ.1.AND.IFAPR.EQ.1) CALL APREM(ICTT,TSURF,IHOUR,NGAGE)
!
!   OUTLIER REMOVAL
!
      DO 200 IBIN=1,NOK
      I=IOK(IBIN)
      J=JOK(IBIN)
!
      IF(RADAR(I,J).GT.RMAX) CALL OUTREM(I,J)
  200 CONTINUE
!
      RETURN
      END
