      subroutine readgg(ihour,ngaghr,ngagmh,npseudo,ngrep,ngage,              &
                        nhrtd,date)
!
!   This subroutine reads the gage precip data
!   It checks for gage - radar distances  > 131 hrap bins.
!     If such a gage is found, a warning message
!     is printed and the gage is not added to the hourly gage list.
!
!   calling subroutine: rdprcp
!   subroutines called: fetch_pseudo,fetch_gagrad,fetch_loc,clselcur,
!                       init_cur_pse,init_cur_gag,llc2dd,ll2hrap
!
!   ngage = total number of gages reporting for radar and current
!             date/hour
!   npseudo = number of pseudo gages for current hour
!   ngaghr = number of hourly gage reports generated by siipp for
!             radar and current date/hour
!   ngagmh = number of multiple hourly gage reports for radar and
!               current date/hour
!   ngrep = total number of hourly gage reports (hourly + time distributed
!              multiple hourly)
!   nhrtd = total number of gages in list (hourly + multiple hourly +
!             time distributed multiple hourly gages)
!   hr1gag = hourly gage report array with nhrtd values for each hour
!            - time distributed hourly values are at the bottom of
!               the list
!            - multiple hourly values with index values between 1 and
!               ngage have value = -99.
!   hrmgag = multiple hourly (durations > 1 hour) gage report array
!              with ngagmh values
!   idurmh = duration of report for each multiple hourly gage for each hour
!   indmh = index for each multiple hourly gage reporting during each hour
!   xlat,xlon = lat,lon for gages with data for current hour
!   idate = integer date of data being processed
!   irc = return code from informix related esql subroutines
!
      character gid*8,clat*9,clon*9,clt*6,cln*7
      character stid(6000)*8
      character date*10,outdir*180
      real apcp(6000),alat(6000),alon(6000)
      integer*2 ih2,idur
      include 'ppinp'
      include 'gagloc'
      include 'hrg'
      include 'mhg'
      include 'lugage'
!
      ngaghr=0
      ngagmh=0
      ngage=0
      npseudo=0
      icnt=0
      ih2=ihour
!
      do 10 i=1,1000
      hr1gag(ihour,i)=-99.0
      hrmgag(ihour,i)=-99.0
      idurmh(ihour,i)=0
      indmh(ihour,i)=0
   10 continue
!
!   *** pseudo gage processing ***
!cc turning this off - MEB
!
!   *** real gage processing ***
!
!
      irc=0
      ngaghr=icnt
!
!   get gage data pathname
!
         outdir = ' '
         call getenv('ST2_ST1',outdir)
         lendir = index(outdir,' ') -1
         if (lendir.le.0) lendir = len(outdir)
         filgag=outdir(1:lendir)//'/gage.'//radid//date//'Z'
!
         open(lugag,file=filgag,form='unformatted')
!
!   read gage data
!   check for distances > 131 hrap bins from radar
!
      read(lugag) ktot,iyr,imn,iday,ihrget
      read(lugag) (apcp(i),i=1,ktot)
      read(lugag) (alat(i),i=1,ktot)
      read(lugag) (alon(i),i=1,ktot)
      read(lugag) (stid(i),i=1,ktot)
      do iblah=1,ktot
          xlt=alat(iblah)
          xln=alon(iblah)
          gid=stid(iblah)
          lenid=8
          ih=0
          jh=0
          gagval=apcp(iblah)
	  call ll2hrap(xlt,xln,ih,jh)
!
            if(ih.le.131.and.jh.le.131.and.ih.gt.0.and.jh.gt.0) then
		  icnt=icnt+1
		  gageid(icnt)='        '
		  gageid(icnt)=gid(1:lenid)
		  xlat(icnt)=xlt
		  xlon(icnt)=xln
		  ngaghr=ngaghr + 1
		  hr1gag(ihour,icnt)=gagval
		  ihloc(icnt)=ih
		  jhloc(icnt)=jh
	       else
!MEB TIRED OF LOOKING AT THIS
!MEB	  write(6,16) gid,gagval,ih,jh
	       end if
      enddo
!
      ngage=icnt
      nhrtd=ngage + ngagmh
      ngrep=ngaghr + ngagmh
!
      if(ngaghr.eq.0) write(6,1)
      if(ngagmh.eq.0) write(6,2)
!
!   close cursor for gagrad table
!
      return
    1 format(/,3x,'*** NO HOURLY GAGES REPORTING ***')
    2 format(/,3x,'*** NO MULTIPLE HOURLY GAGES REPORTING ***')
    9 format(/,2x,'*** gage station missing ',a8)
   16 format(/,2x,'***WARNING -- gage ',a8,1x,'value=',f6.1,1x,               &
         'ihrap/jhrap=',i3,1x,i3,' is at outside radar umbrella')
      END
