      SUBROUTINE STATGG(IHOUR,XMGAG,XMXG,NGAGHR)
!
!   THIS SUBROUTINE CALCULATES THE GAGE RELATED STATISTICS
!   CALLING SUBROUTINE: MNSTAT
!
      INCLUDE 'hrg'
!
      IF(NGAGHR.GT.0) THEN
         XG=0.0
         XMXG=HR1GAG(IHOUR,1)
!
         DO 200 I=1,1000
         GAG=HR1GAG(IHOUR,I)
         IF(GAG.NE.-99.) XG=XG + GAG
         IF(GAG.GT.XMXG) XMXG=GAG
  200    CONTINUE
!
         XMGAG=XG/NGAGHR
      ELSE
         XMGAG=-99.
         XMXG=-99.
      END IF
!
      WRITE(6,1) XMGAG,XMXG
      RETURN
    1 FORMAT(/,3X,'MEAN GAGE VALUE =',F5.1,1X,'MM',3X,'MAX GAGE',             &
         1X,'VALUE =',F5.1,1X,'MM')
      END
